import axios, { AxiosError } from 'axios';

export interface CreateDealPayload {
  title: string;
  goal: string;
  city: string;
}

export interface Bitrix24DealFields {
  TITLE: string;
  [key: string]: string | number | undefined;
}

export interface Bitrix24Response {
  result?: number;
  error?: string;
  error_description?: string;
}

/**
 * Creates a deal in Bitrix24 via REST API webhook.
 *
 * Custom fields must be pre-created in your Bitrix24 account.
 * Field names like UF_CRM_XXXXXXXXXX are auto-generated by Bitrix24
 * when you create custom fields — update the env vars accordingly.
 *
 * Required env variables:
 *  BITRIX24_WEBHOOK_URL  — full webhook URL, e.g.
 *    https://your-domain.bitrix24.ru/rest/1/xxxxxxxxxxxxxxxx
 *  BITRIX24_FIELD_GOAL   — API code of "Цель обращения" field
 *  BITRIX24_FIELD_CITY   — API code of "Город обращения" field
 */
export async function createDeal(payload: CreateDealPayload): Promise<number> {
  const webhookUrl = process.env.BITRIX24_WEBHOOK_URL;

  if (!webhookUrl) {
    throw new Error('BITRIX24_WEBHOOK_URL is not configured in environment variables.');
  }

  const goalField = process.env.BITRIX24_FIELD_GOAL;
  const cityField = process.env.BITRIX24_FIELD_CITY;

  if (!goalField || !cityField) {
    throw new Error(
      'Custom field codes are not configured. Set BITRIX24_FIELD_GOAL and BITRIX24_FIELD_CITY in .env'
    );
  }

  const fields: Bitrix24DealFields = {
    TITLE: payload.title,
    [goalField]: payload.goal,
    [cityField]: payload.city,
  };

  const url = `${webhookUrl.replace(/\/$/, '')}/crm.deal.add.json`;

  try {
    const response = await axios.post<Bitrix24Response>(url, {
      fields,
      params: { REGISTER_SONET_EVENT: 'Y' },
    });

    const data = response.data;

    if (data.error) {
      throw new Error(`Bitrix24 API error: ${data.error} — ${data.error_description}`);
    }

    if (!data.result) {
      throw new Error('Bitrix24 returned unexpected response: no deal ID.');
    }

    return data.result;
  } catch (err) {
    if (err instanceof AxiosError) {
      const msg = err.response?.data?.error_description || err.message;
      throw new Error(`Request to Bitrix24 failed: ${msg}`);
    }
    throw err;
  }
}
